ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER ALUMNO identified BY ALUMNO;
GRANT CONNECT, RESOURCE, DBA TO ALUMNO;

CREATE TABLE PROFESOR (
dni					VARCHAR2(20),
nombre				VARCHAR2(30),
titulacion			VARCHAR2(20),
direccion			VARCHAR2(30),
sueldo				NUMBER(10),
fecha_inicio		DATE,
fecha_fin			DATE,

CONSTRAINT PK_dni PRIMARY KEY(dni)

);


CREATE TABLE CURSO (
Cod_unico			VARCHAR2(20),
nombre				VARCHAR2(20),
titulacion			VARCHAR2(20),
direccion			VARCHAR2(30),
sueldo				NUMBER(10),
num_horas_curso		NUMBER(20),
dni_profesor		VARCHAR(20),

CONSTRAINT PK_cod_unico PRIMARY KEY(Cod_unico),
CONSTRAINT FK_dni_profesor FOREIGN KEY(dni_profesor) REFERENCES PROFESOR(dni)
);


CREATE TABLE ALUMNO (
DNI					VARCHAR2(20),
Direccion			VARCHAR2(30),
Nombre				VARCHAR2(20),
Apellidos			VARCHAR2(30),
FechaNacimiento		DATE,
Sexo				VARCHAR2(5),
Cod_unico			VARCHAR2(20),

CONSTRAINT PK_DNI2 PRIMARY KEY(DNI),
CONSTRAINT FK_Cod_unico FOREIGN KEY(Cod_unico) REFERENCES CURSO(Cod_unico)
);


ALTER TABLE ALUMNO MODIFY Cod_unico NOT NULL;
ALTER TABLE CURSO MODIFY num_horas_curso NOT NULL;
ALTER TABLE PROFESOR MODIFY sueldo NOT NULL;
ALTER TABLE CURSO MODIFY nombre VARCHAR2(20) UNIQUE;
ALTER TABLE PROFESOR MODIFY nombre VARCHAR2(30) UNIQUE;
ALTER TABLE PROFESOR ADD CONSTRAINT CK_cronologia CHECK(fecha_inicio < fecha_fin);
ALTER TABLE ALUMNO ADD CONSTRAINT CK_sexo CHECK(sexo IN 'M' AND sexo IN 'H');
--ALTER TABLE ALUMNO DROP CONSTRAINT CK_sexo;--
