--EJERCICIO 1
SELECT COUNT(A.COSTEBASICO)
FROM ASIGNATURA A;

--EJERCICIO 2
SELECT COUNT(A.IDASIGNATURA), T.NOMBRE 
FROM ASIGNATURA A, TITULACION T
WHERE T.IDTITULACION = A.IDTITULACION
GROUP BY T.NOMBRE;

--EJERCICIO 3
SELECT T.NOMBRE, SUM(COSTEBASICO)
FROM ASIGNATURA A, TITULACION T
WHERE T.IDTITULACION = A.IDTITULACION 
GROUP BY T.NOMBRE;

--EJERCICIO 4
SELECT T.NOMBRE, (A.COSTEBASICO * 0.07 + A.COSTEBASICO) AS COSTEBASICO
FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION = A.IDTITULACION 
AND T.NOMBRE = 'Matematicas';

--EJERCICIO 5
SELECT A.IDASIGNATURA, COUNT(AA.IDALUMNO)
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY A.IDASIGNATURA;

--EJERCICIO 6
SELECT A.NOMBRE, A.IDASIGNATURA, COUNT(AA.IDALUMNO)
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY A.IDASIGNATURA, A.NOMBRE;

--EJERCICIO 7
SELECT P.NOMBRE, SUM(ASI.COSTEBASICO * (0.10 * AA.NUMEROMATRICULA) + ASI.COSTEBASICO) AS PRECIO_TOTAL
FROM PERSONA P, ALUMNO A, ALUMNO_ASIGNATURA AA, ASIGNATURA ASI
WHERE P.DNI = A.DNI 
AND A.IDALUMNO = AA.IDALUMNO 
AND ASI.IDASIGNATURA = AA.IDASIGNATURA 
GROUP BY P.NOMBRE;

--EJERCICIO 8
SELECT AVG(A.COSTEBASICO)
FROM TITULACION T, ASIGNATURA A, ALUMNO_ASIGNATURA AA
WHERE T.IDTITULACION = A.IDTITULACION 
AND A.IDASIGNATURA = AA.IDASIGNATURA 
AND AA.NUMEROMATRICULA = 1 
AND A.COSTEBASICO > 60;

--EJERCICIO 9
SELECT T.NOMBRE
FROM TITULACION T, ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE T.IDTITULACION = A.IDTITULACION 
AND A.IDASIGNATURA = AA.IDASIGNATURA 
AND AL.IDALUMNO = AA.IDALUMNO
GROUP BY T.NOMBRE 
HAVING COUNT(AL.IDALUMNO) > 3;

--EJERCICIO 10
SELECT P.CIUDAD, COUNT(P.DNI) AS PERSONAS
FROM PERSONA P
GROUP BY P.CIUDAD;

--EJERCICIO 11
SELECT PE.NOMBRE, COUNT(A.IDASIGNATURA) AS NUMERO_ASIGNATURA
FROM ASIGNATURA A, PROFESOR P, PERSONA PE
WHERE PE.DNI = P.DNI 
AND P.IDPROFESOR = A.IDPROFESOR 
GROUP BY PE.NOMBRE;

--EJERCICIO 12
SELECT P.NOMBRE, COUNT(AL.IDALUMNO) AS ALUMNOS
FROM PERSONA P, PROFESOR PR, ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE P.DNI = PR.DNI 
AND PR.IDPROFESOR = A.IDPROFESOR 
AND A.IDASIGNATURA = AA.IDASIGNATURA 
AND AA.IDALUMNO = AL.IDALUMNO 
GROUP BY P.NOMBRE
HAVING COUNT(AL.IDALUMNO) >= 2;


--EJERCICIO 13
SELECT MAX(SUM(A.COSTEBASICO))
FROM ASIGNATURA A
GROUP BY A.CUATRIMESTRE;

--EJERCICIO 14
SELECT SUM(A.COSTEBASICO)
FROM ASIGNATURA A;

--EJERCICIO 15
SELECT COUNT(A.IDASIGNATURA)
FROM ASIGNATURA A;

--EJERCICIO 16
SELECT MAX(A.COSTEBASICO), MIN(A.COSTEBASICO)
FROM ASIGNATURA A;

--EJERCICIO 17
SELECT COUNT(A.CREDITOS)
FROM ASIGNATURA A;

--EJERCICIO 18
SELECT COUNT(A.CURSO)
FROM ASIGNATURA A;

--EJERCICIO 19
SELECT COUNT(P.CIUDAD)
FROM PERSONA P;

--EJERCICIO 20
SELECT A.NOMBRE, A.CREDITOS * 10 AS NUM_HORAS
FROM ASIGNATURA A;

--EJERCICIO 21
SELECT A.NOMBRE 
FROM ASIGNATURA A, TITULACION T
WHERE A.IDTITULACION IS NULL
GROUP BY A.NOMBRE;

--EJERCICIO 22
SELECT P.NOMBRE AS NOMBRE_COMPLETO, P.APELLIDO, P.TELEFONO, P.DIRECCIONCALLE AS DIRECCION
FROM PERSONA P;

--EJERCICIO 23
SELECT P.NOMBRE, EXTRACT(DAY FROM P.FECHA_NACIMIENTO) + 1 AS FECHA_NACIMIENTO
FROM PERSONA P;

--EJERCICIO 24
SELECT P.NOMBRE, 2022 - EXTRACT(YEAR FROM P.FECHA_NACIMIENTO) AS AÑOS
FROM PERSONA P;

--EJERCICIO 25
SELECT P.NOMBRE, P.APELLIDO 
FROM PERSONA P
WHERE 2022 - EXTRACT(YEAR FROM P.FECHA_NACIMIENTO) > 25;

--EJERCICIO 26
SELECT P.NOMBRE, P.APELLIDO 
FROM PERSONA P, ALUMNO A, PROFESOR PR
WHERE P.DNI = PR.DNI 
AND P.DNI = A.DNI;

--EJERCICIO 27
SELECT SUM(A.CREDITOS)
FROM ASIGNATURA A, TITULACION T
WHERE T.IDTITULACION = A.IDTITULACION AND T.NOMBRE = 'Matematicas';

--EJERCICIO 28
SELECT SUM(A.IDASIGNATURA)
FROM ASIGNATURA A, TITULACION T
WHERE T.NOMBRE = 'Matematicas';

--EJERCICIO 29
SELECT A.COSTEBASICO, P.NOMBRE 
FROM ASIGNATURA A, ALUMNO AL, ALUMNO_ASIGNATURA AA, PERSONA P
WHERE A.IDASIGNATURA = AA.IDASIGNATURA 
AND AA.IDALUMNO = AL.IDALUMNO 
AND AL.DNI = P.DNI;
--EJERCICIO 30
SELECT A.NOMBRE, COUNT(AA.IDALUMNO)
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY A.NOMBRE, A.IDASIGNATURA;


