--EJERCICIO 1
SELECT T.NOMBRE, A.COSTEBASICO
FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION = A.IDTITULACION 
ORDER BY A.COSTEBASICO DESC, T.NOMBRE ASC;

--EJERCICIO 2
SELECT P.NOMBRE, P.APELLIDO
FROM PERSONA P
ORDER BY P.NOMBRE, P.APELLIDO;

--EJERCICIO 3
SELECT A.NOMBRE
FROM ASIGNATURA A, PROFESOR PR, PERSONA P
WHERE A.IDPROFESOR = PR.IDPROFESOR AND PR.DNI = P.DNI AND CIUDAD LIKE 'Sevilla';

--EJERCICIO 4
SELECT P.NOMBRE, P.APELLIDO
FROM ALUMNO A, PERSONA P
WHERE A.DNI = P.DNI;

--EJERCICIO 5
SELECT P.DNI, P.NOMBRE, P.APELLIDO
FROM ALUMNO A, PERSONA P
WHERE A.DNI = P.DNI AND CIUDAD LIKE 'Sevilla';

--EJERCICIO 6
SELECT P.DNI, P.NOMBRE, P.APELLIDO
FROM PERSONA P, ALUMNO A, ALUMNO_ASIGNATURA AA, ASIGNATURA ASI
WHERE P.DNI = A.DNI 
AND (A.IDALUMNO = AA.IDALUMNO AND ASI.NOMBRE = 'Seguridad Vial')
GROUP BY P.DNI, P.NOMBRE, P.APELLIDO;

--EJERCICIO 7
SELECT A.IDTITULACION 
FROM ASIGNATURA A, ALUMNO AL, ALUMNO_ASIGNATURA AA
WHERE A.IDASIGNATURA = AA.IDASIGNATURA 
AND AL.IDALUMNO = AA.IDALUMNO 
AND AA.NUMEROMATRICULA IS NOT NULL 
AND AL.DNI = '20202020A'
GROUP BY A.IDTITULACION;

--EJERCICIO 8
SELECT A.NOMBRE
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL, PERSONA P
WHERE A.IDASIGNATURA = AA.IDASIGNATURA 
AND P.DNI = AL.DNI 
AND AL.IDALUMNO = AA.IDALUMNO 
AND P.NOMBRE = 'Rosa' 
AND P.APELLIDO = 'Garcia';

--EJERCICIO 9
SELECT AL.DNI
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL, PROFESOR PR, PERSONA P
WHERE AL.IDALUMNO = AA.IDALUMNO 
AND P.DNI = PR.DNI 
AND PR.IDPROFESOR = A.IDPROFESOR 
AND A.IDASIGNATURA = AA.IDASIGNATURA 
AND P.NOMBRE = 'Jorge' 
AND P.APELLIDO = 'Saenz';

--EJERCICIO 10
SELECT AL.DNI, P.NOMBRE, P.APELLIDO 
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL, PROFESOR PR, PERSONA P
WHERE P.DNI = AL.DNI
AND AL.IDALUMNO = AA.IDALUMNO 
AND P.DNI = PR.DNI 
AND PR.IDPROFESOR = A.IDPROFESOR 
AND A.IDASIGNATURA = AA.IDASIGNATURA 
AND P.NOMBRE = 'Jorge' 
AND P.APELLIDO = 'Sáenz';

--No es posible sacar este apartado ya que en la union de la tabla perosna con alumno y profesor no pueden ser iguales los dni a la hora de identificar tanto al profesor como a sus alumnos, ademas de que Sáenz esta registrado en l base de datos sin tilde en la 'a'.

--EJERCICIO 11
SELECT T.NOMBRE
FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION = A.IDTITULACION 
AND A.CREDITOS >= 4;

--EJERCICIO 12
SELECT A.NOMBRE, A.CREDITOS, T.NOMBRE
FROM ASIGNATURA A, TITULACION T
WHERE T.IDTITULACION = A.IDTITULACION 
AND A.CUATRIMESTRE = 1;

--EJERCICIO 13
SELECT A.NOMBRE, A.COSTEBASICO, P.NOMBRE 
FROM ASIGNATURA A, PERSONA P, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE A.IDASIGNATURA = AA.IDASIGNATURA AND P.DNI = AL.DNI AND AL.IDALUMNO = AA.IDALUMNO AND A.COSTEBASICO >= 4.5;

--EJERCICIO 14
SELECT PE.NOMBRE
FROM ASIGNATURA A, PROFESOR P, PERSONA PE
WHERE PE.DNI = P.DNI 
AND P.IDPROFESOR = A.IDPROFESOR 
AND A.COSTEBASICO BETWEEN 24 AND 36;

--EJERCICIO 15
SELECT P.NOMBRE 
FROM PERSONA P, ALUMNO A, ALUMNO_ASIGNATURA AA
WHERE P.DNI = A.DNI AND A.IDALUMNO = AA.IDALUMNO AND (AA.NUMEROMATRICULA = 150212 OR AA.NUMEROMATRICULA = 130113 OR(AA.NUMEROMATRICULA = 150212 AND AA.NUMEROMATRICULA = 130113))

--EJERCICIO 16
SELECT A.NOMBRE, T.NOMBRE
FROM ASIGNATURA A, TITULACION T
WHERE A.CUATRIMESTRE = 2
AND A.CREDITOS != 6
AND A.IDTITULACION = T.IDTITULACION;

--EJERCICIO 17
SELECT A.NOMBRE, A.CREDITOS * 10 AS HORAS, AL.DNI 
FROM ASIGNATURA A, PERSONA P, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE A.IDASIGNATURA = AA.IDASIGNATURA AND P.DNI = AL.DNI AND AL.IDALUMNO = AA.IDALUMNO;

--EJERCICIO 18
SELECT P.NOMBRE 
FROM PERSONA P, ALUMNO A, ALUMNO_ASIGNATURA AA
WHERE P.DNI = A.DNI AND A.IDALUMNO = AA.IDALUMNO AND P.VARON = 0 AND P.CIUDAD = 'Sevilla';

--EJERCICIO 19
SELECT A.NOMBRE 
FROM PROFESOR P, ASIGNATURA A
WHERE P.IDPROFESOR = A.IDPROFESOR AND A.CURSO = 1 AND P.IDPROFESOR = 'P101';

--EJERCICIO 20
SELECT P.NOMBRE 
FROM PERSONA P, ALUMNO A, ALUMNO_ASIGNATURA AA
WHERE P.DNI = A.DNI AND A.IDALUMNO = AA.IDALUMNO AND AA.NUMEROMATRICULA >= 3;



