--EJERCICIO 1--
SELECT nombre, creditos FROM ASIGNATURA;

--EJERCICIO 2--
SELECT DISTINCT creditos FROM ASIGNATURA;

--EJERCICIO 3--
SELECT * FROM PERSONA;

--EJERCICIO 4--
SELECT nombre, creditos FROM ASIGNATURA WHERE cuatrimestre = 1;

--EJERCICIO 5--
SELECT nombre, apellido FROM PERSONA WHERE FECHA_NACIMIENTO < TO_DATE('01/01/1975','DD/MM/YYYY');

--EJERCICIO 6--
SELECT nombre, costebasico FROM ASIGNATURA WHERE CREDITOS > 4.5;

--EJERCICIO 7--
SELECT nombre FROM ASIGNATURA WHERE costebasico BETWEEN 25 AND 35;

--EJERCICIO 8--
SELECT IDALUMNO FROM ALUMNO_ASIGNATURA WHERE (IDASIGNATURA = '150212' OR IDASIGNATURA = '130113') OR (IDASIGNATURA = '150212' AND IDASIGNATURA = '130113');

--EJERCICIO 9--
SELECT NOMBRE FROM ASIGNATURA WHERE CUATRIMESTRE  = 2 AND CREDITOS NOT IN 6;

--EJERCICIO 10--
SELECT NOMBRE, APELLIDO FROM PERSONA WHERE APELLIDO LIKE 'G%';

--EJERCICIO 11--
SELECT NOMBRE FROM ASIGNATURA WHERE IDTITULACION IS NULL;

--EJERCICIO 12--
SELECT NOMBRE FROM ASIGNATURA WHERE IDTITULACION IS NOT NULL;

--EJERCICIO 13--
SELECT NOMBRE FROM ASIGNATURA WHERE CREDITOS > 8;

--EJERCICIO 14--
SELECT NOMBRE, CREDITOS * 10 AS HORAS  FROM ASIGNATURA;

--EJERCICIO 15--
SELECT * FROM ASIGNATURA WHERE CUATRIMESTRE = 2 ORDER BY IDASIGNATURA;

--EJERCICIO 16--
SELECT NOMBRE FROM PERSONA WHERE VARON = 0 AND CIUDAD = 'Madrid';

--EJERCICIO 17--
SELECT NOMBRE,TELEFONO FROM PERSONA WHERE TELEFONO LIKE '91%';

--EJERCICIO 18--
SELECT NOMBRE FROM ASIGNATURA WHERE NOMBRE LIKE '%pro%';

--EJERCICIO 19--
SELECT NOMBRE FROM ASIGNATURA WHERE CURSO = 1 AND IDPROFESOR = 'P101';

--EJERCICIO 20--
SELECT IDALUMNO, IDASIGNATURA FROM ALUMNO_ASIGNATURA WHERE NUMEROMATRICULA >= 3;

--EJERCICIO 21--
SELECT NOMBRE, COSTEBASICO, COSTEBASICO*0.1 AS PRIMERAREPETICION, COSTEBASICO * 0.3 AS SEGUNDAREPETICION, COSTEBASICO * 0.6 AS TERCERAREPETICION FROM ASIGNATURA;

--EJERCICIO 22--
SELECT * FROM PERSONA WHERE EXTRACT(YEAR FROM FECHA_NACIMIENTO) < 1970;

--EJERCICIO 23--
SELECT DISTINCT DNI FROM PROFESOR;

--EJERCICIO 24--
SELECT IDALUMNO FROM ALUMNO_ASIGNATURA WHERE IDASIGNATURA = 130122;

--EJERCICIO 25--
SELECT DISTINCT IDASIGNATURA FROM ALUMNO_ASIGNATURA;

--EJERCICIO 26--
SELECT NOMBRE FROM ASIGNATURA WHERE CREDITOS > 4 AND (CUATRIMESTRE = 1 OR CURSO = 1);

--EJERCICIO 27--
SELECT DISTINCT IDTITULACION FROM ASIGNATURA WHERE IDTITULACION IS NOT NULL;


--EJERCICIO 28--
SELECT DNI FROM PERSONA WHERE (APELLIDO LIKE '%G%')OR(APELLIDO LIKE '%g%');

--EJERCICIO 29--
SELECT NOMBRE FROM PERSONA WHERE VARON = 1 AND EXTRACT(YEAR FROM FECHA_NACIMIENTO) > 1970 AND CIUDAD LIKE 'M%';



